import { app, BrowserWindow, ipcMain, screen, protocol, dialog, shell, net } from 'electron';
import fs from 'fs';
import { createServer, type Server as HttpServer } from 'http';
import path from 'path';
import { Readable } from 'stream';
import { pathToFileURL } from 'url';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Register custom protocol scheme as privileged BEFORE app is ready
// 'standard: true' is required so Chrome's <video> tags can stream media correctly,
// but we use a dummy hostname ('media') in the URL to prevent absolute path parsing issues.
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'local-media',
    privileges: {
      standard: true,
      bypassCSP: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
    },
  },
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
    },
  },
]);

// Whether we are in dev (webpack dev server) or production (packaged asar)
const isDev = MAIN_WINDOW_WEBPACK_ENTRY.startsWith('http');
let pendingDeepLink: string | null = null;
let pendingAuthToken: string | null = null;
const DESKTOP_AUTH_TIMEOUT_MS = 5 * 60 * 1000;

const getWebAppBaseUrl = () => {
  const configuredAuthUrl = process.env.BETTER_AUTH_URL;
  if (configuredAuthUrl) {
    try {
      return new URL(configuredAuthUrl).origin;
    } catch (error) {
      console.warn('Invalid BETTER_AUTH_URL. Falling back to default auth URL.', error);
    }
  }

  return process.env.NODE_ENV === 'development'
    ? 'http://localhost:3001'
    : 'https://present.app';
};

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Prevent multiple instances and set up deep linking
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient('present', process.execPath, [path.resolve(process.argv[1])]);
  }
} else {
  app.setAsDefaultProtocolClient('present');
}

const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', (event, commandLine) => {
    // Windows/Linux handler for deep linking
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
    const url = commandLine.pop();
    if (url && url.startsWith('present://')) {
      handleDeepLink(url);
    }
  });
}

function handleDeepLink(urlStr: string) {
  pendingDeepLink = urlStr;

  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    if (!mainWindow.isVisible()) mainWindow.show();
    mainWindow.focus();
  }

  try {
    const parsedUrl = new URL(urlStr);
    const route = parsedUrl.host || parsedUrl.pathname.replace(/^\/+/, '');

    if (route === 'open' || route === '') {
      pendingDeepLink = null;
      return;
    }

    // BetterAuth callback: the URL contains the session token
    if (parsedUrl.pathname.includes('auth-callback') || parsedUrl.host === 'auth-callback') { 
      const token = parsedUrl.searchParams.get('token');
      if (token) {
        pendingAuthToken = token;
      }
      if (token && mainWindow) {
        if (mainWindow.webContents.isLoading()) {
          pendingDeepLink = urlStr;
          return;
        }
        mainWindow.webContents.send('auth-callback', token);
        pendingDeepLink = null;
      }
    }
  } catch (e) {
    console.error('Failed to parse deep link:', e);
  }
}

// macOS handler for deep linking
app.on('open-url', (event, url) => {
  event.preventDefault();
  if (app.isReady()) {
    handleDeepLink(url);
    return;
  }

  pendingDeepLink = url;
});

let mainWindow: BrowserWindow | null = null;
let outputWindow: BrowserWindow | null = null;
let loopbackAuthServer: HttpServer | null = null;
let loopbackAuthTimeout: NodeJS.Timeout | null = null;

const clearLoopbackAuthFlow = () => {
  if (loopbackAuthTimeout) {
    clearTimeout(loopbackAuthTimeout);
    loopbackAuthTimeout = null;
  }

  if (loopbackAuthServer) {
    loopbackAuthServer.close();
    loopbackAuthServer = null;
  }
};

const buildDesktopAuthLoginUrl = (returnTo: string) => {
  const nextPath = `/auth/desktop/callback?returnTo=${encodeURIComponent(returnTo)}`;
  const webBaseUrl = getWebAppBaseUrl();
  return `${webBaseUrl}/auth/login?next=${encodeURIComponent(nextPath)}`;
};

const sendAuthTokenToRenderer = (token: string) => {
  const deepLink = `present://auth-callback?token=${encodeURIComponent(token)}`;
  handleDeepLink(deepLink);
};

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // In dev, load from webpack dev server. In prod, load via our custom app:// protocol.
  if (isDev) {
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  } else {
    mainWindow.loadURL('app://app/main_window');
  }

  mainWindow.webContents.on('did-finish-load', () => {
    if (pendingDeepLink) {
      const nextDeepLink = pendingDeepLink;
      pendingDeepLink = null;
      handleDeepLink(nextDeepLink);
    }
  });

  // Open the DevTools for debugging.
  mainWindow.webContents.openDevTools();
};

// IPC Handlers for Output Window Management
ipcMain.handle('get-displays', () => {
  return screen.getAllDisplays().map(d => ({
    id: d.id,
    bounds: d.bounds,
    workArea: d.workArea,
    scaleFactor: d.scaleFactor,
    isPrimary: d.id === screen.getPrimaryDisplay().id
  }));
});

ipcMain.handle('open-output-window', () => {
  if (outputWindow) {
    outputWindow.focus();
    return true;
  }

  const displays = screen.getAllDisplays();
  const primaryDisplay = screen.getPrimaryDisplay();
  // Find first external display
  const externalDisplay = displays.find(d => d.id !== primaryDisplay.id);

  outputWindow = new BrowserWindow({
    x: externalDisplay ? externalDisplay.bounds.x : undefined,
    y: externalDisplay ? externalDisplay.bounds.y : undefined,
    width: externalDisplay?.bounds.width || 1280,
    height: externalDisplay?.bounds.height || 720,
    fullscreen: !!externalDisplay,
    autoHideMenuBar: true,
    webPreferences: {
      preload: OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  if (isDev) {
    outputWindow.loadURL(OUTPUT_WINDOW_WEBPACK_ENTRY);
  } else {
    outputWindow.loadURL('app://app/output_window');
  }

  outputWindow.on('closed', () => {
    outputWindow = null;
    if (mainWindow) {
      mainWindow.webContents.send('output-window-closed');
    }
  });

  return true;
});

ipcMain.handle('close-output-window', () => {
  if (outputWindow) {
    outputWindow.close();
    return true;
  }
  return false;
});

// IPC relay: main window sends data to output window
ipcMain.on('send-to-output', (_event, data) => {
  if (outputWindow && !outputWindow.isDestroyed()) {
    outputWindow.webContents.send('output-data', data);
  }
});

// IPC relay: output window tells main window it's ready
ipcMain.on('output-ready', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('output-ready');
  }
});

ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog(mainWindow || undefined, {
    properties: ['openDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }
  const folderPath = result.filePaths[0];
  return {
    id: `folder-${Date.now()}`,
    name: path.basename(folderPath),
    path: folderPath,
  };
});

ipcMain.handle('begin-auth-flow', async () => {
  clearLoopbackAuthFlow();

  return await new Promise<{ ok: boolean; error?: string }>((resolve) => {
    let hasResolved = false;
    const safeResolve = (value: { ok: boolean; error?: string }) => {
      if (hasResolved) {
        return;
      }
      hasResolved = true;
      resolve(value);
    };

    const server = createServer((req, res) => {
      const requestUrl = new URL(req.url ?? '/', `http://${req.headers.host ?? '127.0.0.1'}`);

      if (requestUrl.pathname !== '/callback') {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end('Not Found');
        return;
      }

      const token = requestUrl.searchParams.get('token');
      if (!token) {
        res.writeHead(400, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end('Missing token');
        return;
      }

      res.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-store',
      });
      res.end(
        '<!doctype html><html><body style="font-family:system-ui;padding:24px;">Sign-in complete. You can close this tab and return to Present.</body></html>',
        () => {
          sendAuthTokenToRenderer(token);
          clearLoopbackAuthFlow();
        },
      );
    });

    loopbackAuthServer = server;
    server.once('error', (error) => {
      console.error('Failed to start loopback auth server:', error);
      clearLoopbackAuthFlow();
      safeResolve({ ok: false, error: 'Unable to start local callback server.' });
    });

    server.listen(0, '127.0.0.1', async () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        clearLoopbackAuthFlow();
        safeResolve({ ok: false, error: 'Unable to allocate callback port.' });
        return;
      }

      const returnTo = `http://127.0.0.1:${address.port}/callback`;
      const authUrl = buildDesktopAuthLoginUrl(returnTo);
      loopbackAuthTimeout = setTimeout(() => {
        clearLoopbackAuthFlow();
      }, DESKTOP_AUTH_TIMEOUT_MS);

      try {
        await shell.openExternal(authUrl);
        safeResolve({ ok: true });
      } catch (error) {
        console.error('Failed to open auth URL in browser:', error);
        clearLoopbackAuthFlow();
        safeResolve({ ok: false, error: 'Unable to open the browser for sign-in.' });
      }
    });
  });
});

ipcMain.handle('consume-pending-auth-token', async () => {
  const token = pendingAuthToken;
  pendingAuthToken = null;
  return token;
});

ipcMain.handle('open-external-browser', async (event, urlToOpen) => {
  await shell.openExternal(urlToOpen);
  return true;
});

ipcMain.handle('read-folder', async (_, folderPath: string) => {
  try {
    const files = await fs.promises.readdir(folderPath, { withFileTypes: true });
    const filesWithStats = await Promise.all(
      files
        .filter(f => f.isFile())
        .map(async f => {
          const stats = await fs.promises.stat(path.join(folderPath, f.name));
          return { 
            name: f.name,
            lastModified: stats.mtimeMs
          };
        })
    );
    return filesWithStats;
  } catch (error) {
    console.error('Failed to read folder', error);
    return [];
  }
});

app.on('ready', () => {

  // Custom app:// protocol: serve webpack production assets in a way that gives
  // the renderer a proper origin (app://app) instead of file:// (null origin).
  // This is critical for Clerk SDK initialization in production.
  if (!isDev) {
    protocol.handle('app', (request) => {
      const url = new URL(request.url);
      // url.pathname is e.g. '/main_window' or '/main_window/some-asset.js'
      // MAIN_WINDOW_WEBPACK_ENTRY in prod is like 'file:///path/to/.webpack/renderer/main_window/index.html'
      const mainEntryUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
      const outputEntryUrl = new URL(OUTPUT_WINDOW_WEBPACK_ENTRY);
      const mainDir = path.dirname(mainEntryUrl.pathname);
      const outputDir = path.dirname(outputEntryUrl.pathname);

      const pathname = decodeURIComponent(url.pathname);
      // Strip leading slash on macOS/Linux
      // pathname is like '/main_window' or '/main_window/assets/foo.js'

      let filePath: string;
      if (pathname === '/main_window' || pathname === '/main_window/') {
        // Serve the main window index.html
        filePath = mainEntryUrl.pathname;
      } else if (pathname === '/output_window' || pathname === '/output_window/') {
        // Serve the output window index.html
        filePath = outputEntryUrl.pathname;
      } else if (pathname.startsWith('/main_window/')) {
        // Asset relative to main window dir
        const relativePath = pathname.slice('/main_window/'.length);
        filePath = path.join(mainDir, relativePath);
      } else if (pathname.startsWith('/output_window/')) {
        // Asset relative to output window dir
        const relativePath = pathname.slice('/output_window/'.length);
        filePath = path.join(outputDir, relativePath);
      } else {
        // Fallback: try relative to main dir
        const relativePath = pathname.startsWith('/') ? pathname.slice(1) : pathname;
        filePath = path.join(mainDir, relativePath);
      }

      // On Windows, strip leading slash from /C:/... paths
      if (process.platform === 'win32' && filePath.startsWith('/')) {
        filePath = filePath.slice(1);
      }

      return net.fetch(pathToFileURL(filePath).toString());
    });
  }

  protocol.handle('local-media', async (request) => {
    // When standard: true is used, Chrome strictly requires a hostname. 
    // We use a dummy 'media' hostname via `local-media://media/absolute/path`.
    // The `.pathname` extracts the actual absolute path reliably regardless of OS.
    let filePath = decodeURIComponent(new URL(request.url).pathname);
    
    // On Windows, pathname comes out as `/C:/Users/...`, so strip the leading slash.
    if (process.platform === 'win32' && filePath.startsWith('/')) {
      filePath = filePath.slice(1);
    }
    
    try {
      const stat = await fs.promises.stat(filePath);
      const rangeHeader = request.headers.get('Range');
      
      const ext = path.extname(filePath).toLowerCase();
      let contentType = 'video/mp4';
      if (ext === '.webm') contentType = 'video/webm';
      else if (ext === '.mov') contentType = 'video/quicktime';
      else if (ext === '.mkv') contentType = 'video/x-matroska';
      else if (ext === '.png') contentType = 'image/png';
      else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
      else if (ext === '.gif') contentType = 'image/gif';
      else if (ext === '.webp') contentType = 'image/webp';

      if (!rangeHeader) {
        const stream = fs.createReadStream(filePath);
        const headers = new Headers();
        headers.set('Content-Length', stat.size.toString());
        headers.set('Content-Type', contentType);
        headers.set('Accept-Ranges', 'bytes');
        return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
          status: 200,
          headers
        });
      }

      const parts = rangeHeader.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] && parts[1] !== '' ? parseInt(parts[1], 10) : stat.size - 1;
      const chunksize = (end - start) + 1;

      const stream = fs.createReadStream(filePath, { start, end });
      const headers = new Headers();
      headers.set('Content-Range', `bytes ${start}-${end}/${stat.size}`);
      headers.set('Accept-Ranges', 'bytes');
      headers.set('Content-Length', chunksize.toString());
      headers.set('Content-Type', contentType);

      return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
        status: 206,
        statusText: 'Partial Content',
        headers
      });
    } catch (error) {
      console.error('Error handling local-media request:', error);
      return new Response('Not Found', { status: 404 });
    }
  });

  createWindow();

  const initialDeepLink = process.argv.find((arg) => arg.startsWith('present://'));
  if (initialDeepLink) {
    handleDeepLink(initialDeepLink);
  }
});

app.on('before-quit', () => {
  clearLoopbackAuthFlow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
