import { app, BrowserWindow, ipcMain, screen, protocol, dialog, shell, net, Menu, type MenuItemConstructorOptions } from 'electron';
import fs from 'fs';
import { createServer, type Server as HttpServer } from 'http';
import path from 'path';
import { Readable } from 'stream';
import { pathToFileURL } from 'url';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Register custom protocol scheme as privileged BEFORE app is ready
// 'standard: true' is required so Chrome's <video> tags can stream media correctly,
// but we use a dummy hostname ('media') in the URL to prevent absolute path parsing issues.
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'local-media',
    privileges: {
      standard: true,
      bypassCSP: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
    },
  },
  {
    scheme: 'app',
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      corsEnabled: true,
    },
  },
]);

// Whether we are in dev (webpack dev server) or production (packaged asar)
const isDev = MAIN_WINDOW_WEBPACK_ENTRY.startsWith('http');
let pendingDeepLink: string | null = null;
let pendingAuthToken: string | null = null;
const DESKTOP_AUTH_TIMEOUT_MS = 5 * 60 * 1000;
const SUPPORTED_BIBLE_EXTENSIONS = new Set(['.xml', '.json', '.zip']);
const KNOWN_BIBLE_CODES = [
  'NRSVCE',
  'NRSVA',
  'NRSV',
  'NKJV',
  'TNIV',
  'AMPC',
  'HCSB',
  'NIrV',
  'NABRE',
  'RSVCE',
  'KJV',
  'NIV',
  'ESV',
  'NASB',
  'NLT',
  'RSV',
  'AMP',
  'MSG',
  'CSB',
  'NCV',
  'GNT',
  'CEV',
  'TPT',
  'VOICE',
  'TLB',
  'PHILLIPS',
  'MOUNCE',
  'NET',
  'ISV',
  'LEB',
  'WEB',
  'ASV',
  'YLT',
  'DARBY',
  'AKJV',
  'RV',
  'ERV',
  'BBE',
  'DRA',
  'JB',
  'NJB',
  'GW',
  'JUB',
  'MEV',
  'NOG',
  'TLV',
  'CEB',
  'CJB',
  'EHV',
  'GNV',
  'ICB',
  'NLV',
  'BSB',
  'BRG',
  'EASY',
  'EXB',
];

type BundledBibleFile = {
  id: string;
  code: string;
  name: string;
  filePath: string;
  sizeBytes: number;
};

const inferBibleCodeFromName = (fileNameBase: string): string => {
  const upperBase = fileNameBase.toUpperCase();
  const knownCode = KNOWN_BIBLE_CODES.find((code) => upperBase.includes(code));
  if (knownCode) {
    return knownCode;
  }

  const compact = fileNameBase.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
  if (compact.length >= 2 && compact.length <= 8) {
    return compact;
  }

  return 'BIBLE';
};

const formatBibleName = (fileNameBase: string): string => {
  const spaced = fileNameBase
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return spaced.length > 0 ? spaced : 'Bible';
};

const resolveBundledBibleDirectories = (): string[] => {
  const candidates = new Set<string>([
    path.join(process.resourcesPath, 'bible'),
    path.join(app.getAppPath(), 'bible'),
    path.resolve(process.cwd(), 'apps/desktop/bible'),
    path.resolve(process.cwd(), 'bible'),
  ]);
  return Array.from(candidates);
};

const isPathWithinRoot = (candidatePath: string, rootPath: string): boolean => {
  const relative = path.relative(rootPath, candidatePath);
  return relative === '' || (!relative.startsWith('..') && !path.isAbsolute(relative));
};

const getExistingBundledBibleRoots = async (): Promise<string[]> => {
  const roots: string[] = [];
  for (const directory of resolveBundledBibleDirectories()) {
    try {
      const stats = await fs.promises.stat(directory);
      if (!stats.isDirectory()) {
        continue;
      }
      roots.push(await fs.promises.realpath(directory));
    } catch {
      // ignore missing candidate roots
    }
  }
  return roots;
};

const discoverBundledBibles = async (): Promise<BundledBibleFile[]> => {
  const discovered = new Map<string, BundledBibleFile>();

  for (const directory of resolveBundledBibleDirectories()) {
    try {
      const stats = await fs.promises.stat(directory);
      if (!stats.isDirectory()) {
        continue;
      }

      const entries = await fs.promises.readdir(directory, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isFile()) {
          continue;
        }

        const ext = path.extname(entry.name).toLowerCase();
        if (!SUPPORTED_BIBLE_EXTENSIONS.has(ext)) {
          continue;
        }

        const fullPath = path.resolve(directory, entry.name);
        const fileStats = await fs.promises.stat(fullPath);
        const fileNameBase = path.basename(entry.name, ext);
        const code = inferBibleCodeFromName(fileNameBase);
        const name = formatBibleName(fileNameBase);

        discovered.set(fullPath, {
          id: `${code.toLowerCase()}-${fileStats.size}-${Math.round(fileStats.mtimeMs)}`,
          code,
          name,
          filePath: fullPath,
          sizeBytes: fileStats.size,
        });
      }
    } catch {
      // ignore missing directories
    }
  }

  return Array.from(discovered.values()).sort((a, b) => a.name.localeCompare(b.name));
};

const getWebAppBaseUrl = () => {
  const configuredAuthUrl = process.env.BETTER_AUTH_URL;
  if (configuredAuthUrl) {
    try {
      return new URL(configuredAuthUrl).origin;
    } catch (error) {
      console.warn('Invalid BETTER_AUTH_URL. Falling back to default auth URL.', error);
    }
  }

  return process.env.NODE_ENV === 'development'
    ? 'http://localhost:3001'
    : 'https://present.app';
};

const getMainRendererUrl = (windowType?: 'settings') => {
  const baseUrl = isDev ? MAIN_WINDOW_WEBPACK_ENTRY : 'app://app/main_window';
  if (!windowType) {
    return baseUrl;
  }

  const url = new URL(baseUrl);
  url.searchParams.set('window', windowType);
  return url.toString();
};

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Prevent multiple instances and set up deep linking
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient('present', process.execPath, [path.resolve(process.argv[1])]);
  }
} else {
  app.setAsDefaultProtocolClient('present');
}

const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', (event, commandLine) => {
    // Windows/Linux handler for deep linking
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
    const url = commandLine.pop();
    if (url && url.startsWith('present://')) {
      handleDeepLink(url);
    }
  });
}

function handleDeepLink(urlStr: string) {
  pendingDeepLink = urlStr;

  if (mainWindow) {
    if (mainWindow.isMinimized()) mainWindow.restore();
    if (!mainWindow.isVisible()) mainWindow.show();
    mainWindow.focus();
  }

  try {
    const parsedUrl = new URL(urlStr);
    const route = parsedUrl.host || parsedUrl.pathname.replace(/^\/+/, '');

    if (route === 'open' || route === '') {
      pendingDeepLink = null;
      return;
    }

    // BetterAuth callback: the URL contains the session token
    if (parsedUrl.pathname.includes('auth-callback') || parsedUrl.host === 'auth-callback') { 
      const token = parsedUrl.searchParams.get('token');
      if (token) {
        pendingAuthToken = token;
      }
      if (token && mainWindow) {
        if (mainWindow.webContents.isLoading()) {
          pendingDeepLink = urlStr;
          return;
        }
        mainWindow.webContents.send('auth-callback', token);
        pendingDeepLink = null;
      }
    }
  } catch (e) {
    console.error('Failed to parse deep link:', e);
  }
}

// macOS handler for deep linking
app.on('open-url', (event, url) => {
  event.preventDefault();
  if (app.isReady()) {
    handleDeepLink(url);
    return;
  }

  pendingDeepLink = url;
});

let mainWindow: BrowserWindow | null = null;
let outputWindow: BrowserWindow | null = null;
let settingsWindow: BrowserWindow | null = null;
let loopbackAuthServer: HttpServer | null = null;
let loopbackAuthTimeout: NodeJS.Timeout | null = null;

const getDisplayArea = (display: Electron.Display) => display.bounds.width * display.bounds.height;

const getPreferredOutputDisplay = (): Electron.Display => {
  const displays = screen.getAllDisplays();
  const primary = screen.getPrimaryDisplay();
  const externals = displays.filter((d) => d.id !== primary.id);

  if (externals.length === 0) {
    return primary;
  }

  // Prefer the largest external display (usually the TV/projector).
  externals.sort((a, b) => getDisplayArea(b) - getDisplayArea(a));
  return externals[0];
};

const moveOutputWindowToDisplay = (target: Electron.Display) => {
  if (!outputWindow || outputWindow.isDestroyed()) {
    return;
  }

  const { bounds } = target;
  // Move first (so fullscreen is applied on correct display).
  outputWindow.setBounds({ x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height }, false);

  const isPrimary = target.id === screen.getPrimaryDisplay().id;
  if (isPrimary) {
    if (outputWindow.isFullScreen()) {
      outputWindow.setFullScreen(false);
    }
  } else {
    if (!outputWindow.isFullScreen()) {
      outputWindow.setFullScreen(true);
    }
  }
};

const reconcileOutputWindowDisplay = () => {
  if (!outputWindow || outputWindow.isDestroyed()) {
    return;
  }
  moveOutputWindowToDisplay(getPreferredOutputDisplay());
};

const createSettingsWindow = () => {
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    settingsWindow.focus();
    return;
  }

  settingsWindow = new BrowserWindow({
    width: 1120,
    height: 820,
    minWidth: 980,
    minHeight: 700,
    title: 'Present Settings',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  settingsWindow.loadURL(getMainRendererUrl('settings'));

  settingsWindow.on('closed', () => {
    settingsWindow = null;
  });
};

const openSettingsFromMenu = () => {
  createSettingsWindow();
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    if (settingsWindow.isMinimized()) {
      settingsWindow.restore();
    }
    settingsWindow.focus();
  }
};

const buildApplicationMenu = () => {
  const isMac = process.platform === 'darwin';
  const makeSettingsItem = (): MenuItemConstructorOptions => ({
    label: 'Settings…',
    accelerator: 'CmdOrCtrl+,',
    click: () => openSettingsFromMenu(),
  });

  const template: MenuItemConstructorOptions[] = [];

  if (isMac) {
    const appSubmenu: MenuItemConstructorOptions[] = [
      makeSettingsItem(),
      { type: 'separator' },
      { role: 'hide' },
      { role: 'hideOthers' },
      { role: 'unhide' },
      { type: 'separator' },
      { role: 'quit' },
    ];
    template.push({
      label: app.name,
      submenu: appSubmenu,
    });
  }

  const fileSubmenu: MenuItemConstructorOptions[] = [
    makeSettingsItem(),
    { type: 'separator' },
    isMac ? { role: 'close' } : { role: 'quit' },
  ];

  const editSubmenu: MenuItemConstructorOptions[] = [
    { role: 'undo' },
    { role: 'redo' },
    { type: 'separator' },
    { role: 'cut' },
    { role: 'copy' },
    { role: 'paste' },
  ];
  if (isMac) {
    editSubmenu.push(
      { role: 'pasteAndMatchStyle' },
      { role: 'delete' },
      { role: 'selectAll' },
    );
  } else {
    editSubmenu.push(
      { role: 'delete' },
      { type: 'separator' },
      { role: 'selectAll' },
    );
  }

  const viewSubmenu: MenuItemConstructorOptions[] = [
    { role: 'reload' },
    { role: 'forceReload' },
    { role: 'toggleDevTools' },
    { type: 'separator' },
    { role: 'resetZoom' },
    { role: 'zoomIn' },
    { role: 'zoomOut' },
    { type: 'separator' },
    { role: 'togglefullscreen' },
  ];

  const windowSubmenu: MenuItemConstructorOptions[] = isMac
    ? [
        { role: 'minimize' },
        { role: 'zoom' },
        { type: 'separator' },
        { role: 'front' },
      ]
    : [{ role: 'minimize' }, { role: 'close' }];

  template.push(
    {
      label: 'File',
      submenu: fileSubmenu,
    },
    {
      label: 'Edit',
      submenu: editSubmenu,
    },
    {
      label: 'View',
      submenu: viewSubmenu,
    },
    {
      label: 'Window',
      submenu: windowSubmenu,
    },
  );

  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
};

const clearLoopbackAuthFlow = () => {
  if (loopbackAuthTimeout) {
    clearTimeout(loopbackAuthTimeout);
    loopbackAuthTimeout = null;
  }

  if (loopbackAuthServer) {
    loopbackAuthServer.close();
    loopbackAuthServer = null;
  }
};

const buildDesktopAuthLoginUrl = (returnTo: string) => {
  const nextPath = `/auth/desktop/callback?returnTo=${encodeURIComponent(returnTo)}`;
  const webBaseUrl = getWebAppBaseUrl();
  return `${webBaseUrl}/auth/login?next=${encodeURIComponent(nextPath)}`;
};

const sendAuthTokenToRenderer = (token: string) => {
  const deepLink = `present://auth-callback?token=${encodeURIComponent(token)}`;
  handleDeepLink(deepLink);
};

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 980,
    width: 1560,
    minWidth: 1180,
    minHeight: 760,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // In dev, load from webpack dev server. In prod, load via our custom app:// protocol.
  mainWindow.loadURL(getMainRendererUrl());

  mainWindow.webContents.on('did-finish-load', () => {
    if (pendingDeepLink) {
      const nextDeepLink = pendingDeepLink;
      pendingDeepLink = null;
      handleDeepLink(nextDeepLink);
    }
  });

  // Open the DevTools for debugging.
  mainWindow.webContents.openDevTools();

  mainWindow.on('close', () => {
    if (settingsWindow && !settingsWindow.isDestroyed()) {
      settingsWindow.close();
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
};

// IPC Handlers for Output Window Management
ipcMain.handle('get-displays', () => {
  return screen.getAllDisplays().map(d => ({
    id: d.id,
    bounds: d.bounds,
    workArea: d.workArea,
    scaleFactor: d.scaleFactor,
    isPrimary: d.id === screen.getPrimaryDisplay().id
  }));
});

ipcMain.handle('open-output-window', () => {
  if (outputWindow) {
    outputWindow.focus();
    reconcileOutputWindowDisplay();
    return true;
  }

  const preferredDisplay = getPreferredOutputDisplay();
  const isPrimary = preferredDisplay.id === screen.getPrimaryDisplay().id;

  outputWindow = new BrowserWindow({
    x: preferredDisplay.bounds.x,
    y: preferredDisplay.bounds.y,
    width: preferredDisplay.bounds.width || 1280,
    height: preferredDisplay.bounds.height || 720,
    fullscreen: !isPrimary,
    autoHideMenuBar: true,
    webPreferences: {
      preload: OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  if (isDev) {
    outputWindow.loadURL(OUTPUT_WINDOW_WEBPACK_ENTRY);
  } else {
    outputWindow.loadURL('app://app/output_window');
  }

  outputWindow.on('closed', () => {
    outputWindow = null;
    if (mainWindow) {
      mainWindow.webContents.send('output-window-closed');
    }
  });

  return true;
});

ipcMain.handle('close-output-window', () => {
  if (outputWindow) {
    outputWindow.close();
    return true;
  }
  return false;
});

// IPC relay: main window sends data to output window
ipcMain.on('send-to-output', (_event, data) => {
  if (outputWindow && !outputWindow.isDestroyed()) {
    outputWindow.webContents.send('output-data', data);
  }
});

// IPC relay: output window tells main window it's ready
ipcMain.on('output-ready', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('output-ready');
  }
});

ipcMain.handle('select-folder', async (event) => {
  const parentWindow = BrowserWindow.fromWebContents(event.sender) ?? mainWindow ?? undefined;
  const result = await dialog.showOpenDialog(parentWindow, {
    properties: ['openDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }
  const folderPath = result.filePaths[0];
  return {
    id: `folder-${Date.now()}`,
    name: path.basename(folderPath),
    path: folderPath,
  };
});

ipcMain.handle('begin-auth-flow', async () => {
  clearLoopbackAuthFlow();

  return await new Promise<{ ok: boolean; error?: string }>((resolve) => {
    let hasResolved = false;
    const safeResolve = (value: { ok: boolean; error?: string }) => {
      if (hasResolved) {
        return;
      }
      hasResolved = true;
      resolve(value);
    };

    const server = createServer((req, res) => {
      const requestUrl = new URL(req.url ?? '/', `http://${req.headers.host ?? '127.0.0.1'}`);

      if (requestUrl.pathname !== '/callback') {
        res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end('Not Found');
        return;
      }

      const token = requestUrl.searchParams.get('token');
      if (!token) {
        res.writeHead(400, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end('Missing token');
        return;
      }

      res.writeHead(200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-store',
      });
      res.end(
        '<!doctype html><html><body style="font-family:system-ui;padding:24px;">Sign-in complete. You can close this tab and return to Present.</body></html>',
        () => {
          sendAuthTokenToRenderer(token);
          clearLoopbackAuthFlow();
        },
      );
    });

    loopbackAuthServer = server;
    server.once('error', (error) => {
      console.error('Failed to start loopback auth server:', error);
      clearLoopbackAuthFlow();
      safeResolve({ ok: false, error: 'Unable to start local callback server.' });
    });

    server.listen(0, '127.0.0.1', async () => {
      const address = server.address();
      if (!address || typeof address === 'string') {
        clearLoopbackAuthFlow();
        safeResolve({ ok: false, error: 'Unable to allocate callback port.' });
        return;
      }

      const returnTo = `http://127.0.0.1:${address.port}/callback`;
      const authUrl = buildDesktopAuthLoginUrl(returnTo);
      loopbackAuthTimeout = setTimeout(() => {
        clearLoopbackAuthFlow();
      }, DESKTOP_AUTH_TIMEOUT_MS);

      try {
        await shell.openExternal(authUrl);
        safeResolve({ ok: true });
      } catch (error) {
        console.error('Failed to open auth URL in browser:', error);
        clearLoopbackAuthFlow();
        safeResolve({ ok: false, error: 'Unable to open the browser for sign-in.' });
      }
    });
  });
});

ipcMain.handle('consume-pending-auth-token', async () => {
  const token = pendingAuthToken;
  pendingAuthToken = null;
  return token;
});

ipcMain.handle('open-external-browser', async (event, urlToOpen) => {
  await shell.openExternal(urlToOpen);
  return true;
});

ipcMain.handle('read-folder', async (_, folderPath: string) => {
  try {
    const files = await fs.promises.readdir(folderPath, { withFileTypes: true });
    const filesWithStats = await Promise.all(
      files
        .filter(f => f.isFile())
        .map(async f => {
          const stats = await fs.promises.stat(path.join(folderPath, f.name));
          return { 
            name: f.name,
            lastModified: stats.mtimeMs
          };
        })
    );
    return filesWithStats;
  } catch (error) {
    console.error('Failed to read folder', error);
    return [];
  }
});

ipcMain.handle('list-bundled-bibles', async () => {
  try {
    return await discoverBundledBibles();
  } catch (error) {
    console.error('Failed to list bundled bibles', error);
    return [];
  }
});

ipcMain.handle('read-bundled-bible', async (_, filePath: string) => {
  try {
    if (typeof filePath !== 'string' || filePath.trim().length === 0) {
      throw new Error('Missing file path');
    }

    const requestedPath = path.resolve(filePath);
    const extension = path.extname(requestedPath).toLowerCase();
    if (!SUPPORTED_BIBLE_EXTENSIONS.has(extension)) {
      throw new Error('Unsupported bible file type');
    }

    const roots = await getExistingBundledBibleRoots();
    if (roots.length === 0) {
      throw new Error('No bundled bible directory found');
    }

    const realRequestedPath = await fs.promises.realpath(requestedPath);
    const isAllowed = roots.some((root) => isPathWithinRoot(realRequestedPath, root));
    if (!isAllowed) {
      throw new Error('File path is outside bundled bible directories');
    }

    const fileBuffer = await fs.promises.readFile(realRequestedPath);
    return new Uint8Array(fileBuffer);
  } catch (error) {
    console.error('Failed to read bundled bible', error);
    return null;
  }
});

async function fetchJsonFollowingRedirects(url: string, maxRedirects = 5): Promise<unknown> {
  let currentUrl = url;
  for (let i = 0; i <= maxRedirects; i += 1) {
    const response = await net.fetch(currentUrl, { cache: 'no-store' });
    if (
      response.status >= 300
      && response.status < 400
    ) {
      const location = response.headers.get('location');
      if (!location) {
        throw new Error(`Redirect without location header (${response.status})`);
      }
      currentUrl = new URL(location, currentUrl).toString();
      continue;
    }
    if (!response.ok) {
      throw new Error(`Request failed (${response.status})`);
    }
    return await response.json();
  }
  throw new Error('Too many redirects');
}

ipcMain.handle('fetch-hosted-bible-catalog', async (_, catalogUrl: string) => {
  try {
    if (typeof catalogUrl !== 'string' || catalogUrl.trim().length === 0) {
      throw new Error('Missing catalog URL');
    }
    return await fetchJsonFollowingRedirects(catalogUrl);
  } catch (error) {
    console.error('Failed to fetch hosted bible catalog', error);
    return null;
  }
});

app.on('ready', () => {

  // Custom app:// protocol: serve webpack production assets in a way that gives
  // the renderer a proper origin (app://app) instead of file:// (null origin).
  // This is critical for Clerk SDK initialization in production.
  if (!isDev) {
    protocol.handle('app', (request) => {
      const url = new URL(request.url);
      // url.pathname is e.g. '/main_window' or '/main_window/some-asset.js'
      // MAIN_WINDOW_WEBPACK_ENTRY in prod is like 'file:///path/to/.webpack/renderer/main_window/index.html'
      const mainEntryUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
      const outputEntryUrl = new URL(OUTPUT_WINDOW_WEBPACK_ENTRY);
      const mainDir = path.dirname(mainEntryUrl.pathname);
      const outputDir = path.dirname(outputEntryUrl.pathname);

      const pathname = decodeURIComponent(url.pathname);
      // Strip leading slash on macOS/Linux
      // pathname is like '/main_window' or '/main_window/assets/foo.js'

      let filePath: string;
      if (pathname === '/main_window' || pathname === '/main_window/') {
        // Serve the main window index.html
        filePath = mainEntryUrl.pathname;
      } else if (pathname === '/output_window' || pathname === '/output_window/') {
        // Serve the output window index.html
        filePath = outputEntryUrl.pathname;
      } else if (pathname.startsWith('/main_window/')) {
        // Asset relative to main window dir
        const relativePath = pathname.slice('/main_window/'.length);
        filePath = path.join(mainDir, relativePath);
      } else if (pathname.startsWith('/output_window/')) {
        // Asset relative to output window dir
        const relativePath = pathname.slice('/output_window/'.length);
        filePath = path.join(outputDir, relativePath);
      } else {
        // Fallback: try relative to main dir
        const relativePath = pathname.startsWith('/') ? pathname.slice(1) : pathname;
        filePath = path.join(mainDir, relativePath);
      }

      // On Windows, strip leading slash from /C:/... paths
      if (process.platform === 'win32' && filePath.startsWith('/')) {
        filePath = filePath.slice(1);
      }

      return net.fetch(pathToFileURL(filePath).toString());
    });
  }

  protocol.handle('local-media', async (request) => {
    // When standard: true is used, Chrome strictly requires a hostname. 
    // We use a dummy 'media' hostname via `local-media://media/absolute/path`.
    // The `.pathname` extracts the actual absolute path reliably regardless of OS.
    let filePath = decodeURIComponent(new URL(request.url).pathname);
    
    // On Windows, pathname comes out as `/C:/Users/...`, so strip the leading slash.
    if (process.platform === 'win32' && filePath.startsWith('/')) {
      filePath = filePath.slice(1);
    }
    
    try {
      const stat = await fs.promises.stat(filePath);
      const rangeHeader = request.headers.get('Range');
      
      const ext = path.extname(filePath).toLowerCase();
      let contentType = 'video/mp4';
      if (ext === '.webm') contentType = 'video/webm';
      else if (ext === '.mov') contentType = 'video/quicktime';
      else if (ext === '.mkv') contentType = 'video/x-matroska';
      else if (ext === '.png') contentType = 'image/png';
      else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
      else if (ext === '.gif') contentType = 'image/gif';
      else if (ext === '.webp') contentType = 'image/webp';

      if (!rangeHeader) {
        const stream = fs.createReadStream(filePath);
        const headers = new Headers();
        headers.set('Content-Length', stat.size.toString());
        headers.set('Content-Type', contentType);
        headers.set('Accept-Ranges', 'bytes');
        return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
          status: 200,
          headers
        });
      }

      const parts = rangeHeader.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] && parts[1] !== '' ? parseInt(parts[1], 10) : stat.size - 1;
      const chunksize = (end - start) + 1;

      const stream = fs.createReadStream(filePath, { start, end });
      const headers = new Headers();
      headers.set('Content-Range', `bytes ${start}-${end}/${stat.size}`);
      headers.set('Accept-Ranges', 'bytes');
      headers.set('Content-Length', chunksize.toString());
      headers.set('Content-Type', contentType);

      return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
        status: 206,
        statusText: 'Partial Content',
        headers
      });
    } catch (error) {
      console.error('Error handling local-media request:', error);
      return new Response('Not Found', { status: 404 });
    }
  });

  createWindow();
  buildApplicationMenu();

  // Keep output window on the best available display as displays change (HDMI plug/unplug).
  screen.on('display-added', () => reconcileOutputWindowDisplay());
  screen.on('display-removed', () => reconcileOutputWindowDisplay());
  screen.on('display-metrics-changed', () => reconcileOutputWindowDisplay());

  const initialDeepLink = process.argv.find((arg) => arg.startsWith('present://'));
  if (initialDeepLink) {
    handleDeepLink(initialDeepLink);
  }
});

app.on('before-quit', () => {
  clearLoopbackAuthFlow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
