import { app, BrowserWindow, ipcMain, screen, protocol, dialog } from 'electron';
import fs from 'fs';
import path from 'path';
import { Readable } from 'stream';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_WEBPACK_ENTRY: string;
declare const OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Register custom protocol scheme as privileged BEFORE app is ready
// This is required so videos can stream (range requests) through the protocol.
// 'standard: true' is required so Chrome's <video> tags can stream media correctly,
// but we use a dummy hostname ('media') in the URL to prevent absolute path parsing issues.
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'local-media',
    privileges: {
      standard: true,
      bypassCSP: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
    },
  },
]);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let outputWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// IPC Handlers for Output Window Management
ipcMain.handle('get-displays', () => {
  return screen.getAllDisplays().map(d => ({
    id: d.id,
    bounds: d.bounds,
    workArea: d.workArea,
    scaleFactor: d.scaleFactor,
    isPrimary: d.id === screen.getPrimaryDisplay().id
  }));
});

ipcMain.handle('open-output-window', () => {
  if (outputWindow) {
    outputWindow.focus();
    return true;
  }

  const displays = screen.getAllDisplays();
  const primaryDisplay = screen.getPrimaryDisplay();
  // Find first external display
  const externalDisplay = displays.find(d => d.id !== primaryDisplay.id);

  outputWindow = new BrowserWindow({
    x: externalDisplay ? externalDisplay.bounds.x : undefined,
    y: externalDisplay ? externalDisplay.bounds.y : undefined,
    width: externalDisplay?.bounds.width || 1280,
    height: externalDisplay?.bounds.height || 720,
    fullscreen: !!externalDisplay,
    autoHideMenuBar: true,
    webPreferences: {
      preload: OUTPUT_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  outputWindow.loadURL(OUTPUT_WINDOW_WEBPACK_ENTRY);

  outputWindow.on('closed', () => {
    outputWindow = null;
    if (mainWindow) {
      mainWindow.webContents.send('output-window-closed');
    }
  });

  return true;
});

ipcMain.handle('close-output-window', () => {
  if (outputWindow) {
    outputWindow.close();
    return true;
  }
  return false;
});

// IPC relay: main window sends data to output window
ipcMain.on('send-to-output', (_event, data) => {
  if (outputWindow && !outputWindow.isDestroyed()) {
    outputWindow.webContents.send('output-data', data);
  }
});

// IPC relay: output window tells main window it's ready
ipcMain.on('output-ready', () => {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send('output-ready');
  }
});

ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog(mainWindow || undefined, {
    properties: ['openDirectory'],
  });
  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }
  const folderPath = result.filePaths[0];
  return {
    id: `folder-${Date.now()}`,
    name: path.basename(folderPath),
    path: folderPath,
  };
});

ipcMain.handle('read-folder', async (_, folderPath: string) => {
  try {
    const files = await fs.promises.readdir(folderPath, { withFileTypes: true });
    const filesWithStats = await Promise.all(
      files
        .filter(f => f.isFile())
        .map(async f => {
          const stats = await fs.promises.stat(path.join(folderPath, f.name));
          return { 
            name: f.name,
            lastModified: stats.mtimeMs
          };
        })
    );
    return filesWithStats;
  } catch (error) {
    console.error('Failed to read folder', error);
    return [];
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  protocol.handle('local-media', async (request) => {
    // When standard: true is used, Chrome strictly requires a hostname. 
    // We use a dummy 'media' hostname via `local-media://media/absolute/path`.
    // The `.pathname` extracts the actual absolute path reliably regardless of OS.
    let filePath = decodeURIComponent(new URL(request.url).pathname);
    
    // On Windows, pathname comes out as `/C:/Users/...`, so strip the leading slash.
    if (process.platform === 'win32' && filePath.startsWith('/')) {
      filePath = filePath.slice(1);
    }
    
    try {
      const stat = await fs.promises.stat(filePath);
      const rangeHeader = request.headers.get('Range');
      
      const ext = path.extname(filePath).toLowerCase();
      let contentType = 'video/mp4';
      if (ext === '.webm') contentType = 'video/webm';
      else if (ext === '.mov') contentType = 'video/quicktime';
      else if (ext === '.mkv') contentType = 'video/x-matroska';
      else if (ext === '.png') contentType = 'image/png';
      else if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
      else if (ext === '.gif') contentType = 'image/gif';
      else if (ext === '.webp') contentType = 'image/webp';

      if (!rangeHeader) {
        const stream = fs.createReadStream(filePath);
        const headers = new Headers();
        headers.set('Content-Length', stat.size.toString());
        headers.set('Content-Type', contentType);
        headers.set('Accept-Ranges', 'bytes');
        return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
          status: 200,
          headers
        });
      }

      const parts = rangeHeader.replace(/bytes=/, '').split('-');
      const start = parseInt(parts[0], 10);
      const end = parts[1] && parts[1] !== '' ? parseInt(parts[1], 10) : stat.size - 1;
      const chunksize = (end - start) + 1;

      const stream = fs.createReadStream(filePath, { start, end });
      const headers = new Headers();
      headers.set('Content-Range', `bytes ${start}-${end}/${stat.size}`);
      headers.set('Accept-Ranges', 'bytes');
      headers.set('Content-Length', chunksize.toString());
      headers.set('Content-Type', contentType);

      return new Response(Readable.toWeb(stream) as unknown as ReadableStream, {
        status: 206,
        statusText: 'Partial Content',
        headers
      });
    } catch (error) {
      console.error('Error handling local-media request:', error);
      return new Response('Not Found', { status: 404 });
    }
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
